# Generated by Django 3.0.5 on 2020-05-03 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('miembros', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
            options={
                'permissions': [('Can add comite', 'Puede crear un comité'), ('Can change comite', 'Puede editar el comité'), ('Can delete comite', 'Puede eliminar un comité'), ('Can view comite', 'Puede visualizar un comité')],
            },
        ),
    ]
