# Generated by Django 3.0.5 on 2020-05-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comite',
            options={'default_permissions': (), 'permissions': [('crear_comite', 'crear_comite'), ('eliminar_comite', 'eliminar_comite'), ('ver_comite', 'ver_comite'), ('editar_comite', 'editar_comite'), ('listar_comite', 'listar_comite'), ('agregar_comite_proyecto', 'agregar_comite_proyecto'), ('quitar_comite_proyecto', 'quitar_comite_proyecto'), ('agregar_usuario_comite', 'agregar_usuario_comite'), ('quitar_usuario_comite', 'quitar_usuario_comite')]},
        ),
    ]
