# Generated by Django 3.0.5 on 2020-05-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0004_auto_20200429_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comite',
            options={'permissions': [('Can add proyecto', 'Puede crear un comité'), ('Can change proyecto', 'Puede editar el comité'), ('Can delete proyecto', 'Puede eliminar un comité'), ('Can view proyecto', 'Puede visualizar un comité')]},
        ),
    ]
