# Generated by Django 3.0.5 on 2020-05-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0005_auto_20200501_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comite',
            options={'permissions': [('Can add comite', 'Puede crear un comité'), ('Can change comite', 'Puede editar el comité'), ('Can delete comite', 'Puede eliminar un comité'), ('Can view comite', 'Puede visualizar un comité')]},
        ),
    ]
