# Generated by Django 3.0.5 on 2020-05-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'permissions': [('crear_proyecto', 'crear_proyecto'), ('iniciar_proyecto', 'iniciar_proyecto'), ('finalizar_proyecto', 'finalizar_proyecto'), ('cancelar_proyecto', 'cancelar_proyecto'), ('ver_proyecto', 'ver_proyecto'), ('eliminar_proyecto', 'eliminar_proyecto'), ('editar_proyecto', 'editar_proyecto'), ('detalles_proyecto', 'detalles_proyecto')]},
        ),
    ]
