# Generated by Django 3.0.5 on 2020-04-24 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20200403_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='ultima_modificación',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
