# Generated by Django 3.0.5 on 2020-04-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_proyecto_ultima_modificación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='ultima_modificación',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
