# Generated by Django 3.0.5 on 2020-04-26 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_proyecto_comite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='comite',
        ),
    ]
