# Generated by Django 3.0.5 on 2020-04-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_remove_proyecto_comite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='ultima_modificación',
            new_name='ultima_modificacion',
        ),
    ]
