# Generated by Django 3.0.5 on 2020-04-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20200426_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tiene_comite',
            field=models.BooleanField(default=False),
        ),
    ]
