# Generated by Django 3.0.5 on 2020-04-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_proyecto_tiene_comite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tiene_comite',
        ),
    ]
