# Generated by Django 3.0.5 on 2020-05-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20200501_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('Can add proyecto', 'Puede crear un proyecto'), ('Can change proyecto', 'Puede editar el proyecto'), ('Can delete proyecto', 'Puede eliminar un proyecto'), ('Can view proyecto', 'Puede visualizar un proyecto')]},
        ),
    ]
