# Generated by Django 3.0.6 on 2020-05-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('roles', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('crear_usuario', 'crear_usuario'), ('editar_usuario', 'editar_usuario'), ('agregrar_usuario_proyecto', 'agregrar_usuario_proyecto'), ('eliminar_usuario', 'eliminar_usuario'), ('crear_rol', 'crear_rol'), ('eliminar_rol', 'eliminar_rol'), ('asignar_rol', 'asignar_rol'), ('ver_rol', 'ver_rol'), ('listar_rol', 'listar_rol'), ('editar_rol', 'editar_rol'), ('agregar_usuario_fase', 'agregar_usuario_fase'), ('quitar_usuario_proyecto', 'quitar_usuario_proyecto'), ('quitar_usuario_fase', 'quitar_usuario_fase')],
                'default_permissions': (),
            },
        ),
    ]
