# Generated by Django 3.0.4 on 2020-04-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('roles', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
