# Generated by Django 3.0.5 on 2020-05-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'default_permissions': (), 'permissions': [('crear_usuario', 'crear_usuario'), ('editar_usuario', 'editar_usuario'), ('agregrar_usuario_proyecto', 'agregrar_usuario_proyecto'), ('eliminar_usuario', 'eliminar_usuario'), ('crear_rol', 'crear_rol'), ('eliminar_rol', 'eliminar_rol'), ('asignar_rol', 'asignar_rol'), ('ver_rol', 'ver_rol'), ('listar_rol', 'listar_rol'), ('editar_rol', 'editar_rol'), ('agregar_usuario_fase', 'agregar_usuario_fase'), ('quitar_usuario_proyecto', 'quitar_usuario_proyecto'), ('quitar_usuario_fase', 'quitar_usuario_fase')]},
        ),
    ]
