# Generated by Django 3.0.5 on 2020-05-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('Can add proyecto', 'Puede registrar un usuario'), ('Can change proyecto', 'Puede modificar el usuario'), ('Can delete proyecto', 'Puede eliminar un usuario'), ('Can view proyecto', 'Puede visualizar un usuario')]},
        ),
    ]
