# Generated by Django 3.0.5 on 2020-05-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200501_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('Can add usuario', 'Puede registrar un usuario'), ('Can change usuario', 'Puede modificar el usuario'), ('Can delete usuario', 'Puede eliminar un usuario'), ('Can view usuario', 'Puede visualizar un usuario')]},
        ),
    ]
