# Generated by Django 3.0.6 on 2020-05-12 18:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=30)),
                ('miembros', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
            options={
                'permissions': [('crear_fase', 'crear_fase'), ('aprobar_fase', 'aprobar_fase'), ('editar_fase', 'editar_fase'), ('eliminar_fase', 'eliminar_fase'), ('listar_fase', 'listar_fase'), ('cambio_estado_fase', 'cambio_estado_fase'), ('ver_fase', 'ver_fase'), ('detalles_fase', 'detalles_fase')],
                'default_permissions': (),
            },
        ),
    ]
