# Generated by Django 3.0.7 on 2020-08-21 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=30)),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'permissions': [('crear_fase', 'crear_fase'), ('aprobar_fase', 'aprobar_fase'), ('editar_fase', 'editar_fase'), ('eliminar_fase', 'eliminar_fase'), ('listar_fase', 'listar_fase'), ('cambio_estado_fase', 'cambio_estado_fase'), ('ver_fase', 'ver_fase'), ('detalles_fase', 'detalles_fase')],
                'default_permissions': (),
            },
        ),
    ]
