# Generated by Django 3.0.5 on 2020-05-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'default_permissions': (), 'permissions': [('crear_fase', 'crear_fase'), ('aprobar_fase', 'aprobar_fase'), ('editar_fase', 'editar_fase'), ('eliminar_fase', 'eliminar_fase'), ('listar_fase', 'listar_fase'), ('cambio_estado_fase', 'cambio_estado_fase'), ('ver_fase', 'ver_fase'), ('detalles_fase', 'detalles_fase')]},
        ),
    ]
