#!/usr/bin/bash
echo -e "\n=========================== Bienvenido! =========================="

echo -e "\nEstamos preparando el despliegue de producción del Proyecto SGCAS!"

echo -e "\n=== Accediendo a clonar el proyecto del repositorio remoto Github ==="
echo -e "\n=== Creando directorio del proyecto en maquina local... ==="
sleep 5

if [ -d "/home/victor/SGCAS" ]
then
	rm -rf SGCAS
	cd /home/victor/Projects/SGCAS/scripts
	python3 produccion.py
	cd /home/victor
	# Baja el TAG IT5 o especificamente un tag  
	git clone -b IT5 --single-branch git://github.com/geekpy03/IS2-Equipo07.git SGCAS
	cd /home/victor/Projects/SGCAS/scripts
	python3 produccion.py
else
   	# Baja el TAG IT5 o especificamente un tag  
	cd /home/victor/Projects/SGCAS/scripts
	echo -e "\n\n=== Accediendo a postgreSQL y creando la base de datos de produccion ==="
	python3 produccion.py
	cd /home/victor
	git clone -b IT5 --single-branch git://github.com/geekpy03/IS2-Equipo07.git SGCAS
fi

echo -e "\n=== CLONACIÓN CULMINADO SATISFACTORIAMENTE!!! ==="
echo -e "\n=== Directorio del proyecto en maquina local... ==="
echo -e "\n=== Creando entorno virtual ==="
sleep 6
python3 -m venv ~/SGCAS/venv

if [ ~/SGCAS/venv ]
then 
	echo -e "\n=== ENTORNO VIRTUAL CREADO SATISFACTORIAMENTE! ==="
else
	echo -e "\nError! no se ha podido completar la acción!!!"
fi

cd /home/victor/SGCAS/deployment
mkdir media

cd /home/victor/SGCAS/apps

# # Creando las carpetas para " makemigrations y migrate"
mkdir comite/migrations
touch comite/migrations/__init__.py
mkdir fase/migrations
touch fase/migrations/__init__.py
mkdir item/migrations
touch item/migrations/__init__.py
mkdir linea_base/migrations
touch linea_base/migrations/__init__.py
mkdir proyecto/migrations
touch proyecto/migrations/__init__.py
mkdir rol/migrations
touch rol/migrations/__init__.py
mkdir tipo_item/migrations
touch tipo_item/migrations/__init__.py
mkdir usuario/migrations
touch usuario/migrations/__init__.py

cd /home/victor/SGCAS/venv

source ./bin/activate
PS1="(`basename \"$VIRTUAL_ENV\"`)\e[1;34m:/\W\033[00m$ "
sleep 2

echo -e "\n=== Entorno virtual activado ==="

cd /home/victor/SGCAS/
echo -e "\n=== Preparando instalación de dependencias...porfavor aguarde! ==="
sleep 6
pip install -r requirements.txt

echo -e "\n=== Realizando las migraciones a la base de datos...Aguarde un momento! ==="
sleep 6
# # migrate
cd /home/victor/SGCAS/
python manage.py makemigrations
python manage.py migrate


echo -e "\n=== Poblando la base de datos con los escenarios ==="
python manage.py loaddata fixtures/db.json

# Configurar los parametros de apache y localhost 

cd /etc/apache2/sites-available
sudo rm 000-default.conf
cd /home/victor/Projects/SGCAS/scripts
sudo cp 000-default.conf /etc/apache2/sites-available
sudo sudo service apache2 start
sudo sudo service apache2 restart
echo -e "\n=== Generando documentación ==="
cd /home/victor/SGCAS/apps/comite
pycco *.py -p
cd /home/victor/SGCAS/apps/fase
pycco *.py -p
cd /home/victor/SGCAS/apps/item
pycco *.py -p
cd /home/victor/SGCAS/apps/linea_base
pycco *.py -p
cd /home/victor/SGCAS/apps/mensajes
pycco *.py -p
cd /home/victor/SGCAS/apps/proyecto
pycco *.py -p
cd /home/victor/SGCAS/apps/rol
pycco *.py -p
cd /home/victor/SGCAS/apps/tipo_item
pycco *.py -p
cd /home/victor/SGCAS/apps/usuario
pycco *.py -p

echo -e "\n=== Documentación Generada! Abriendo en el navegador ==="
cd /home/victor/Projects/SGCAS/scripts
python open_doc.py

echo -e "\n\n=== Felicidades!!! El proyecto ya ha sido desplegado en producción de Apache. ==="
echo -e "\n\n=== Abriendo el navegador en la siguiente dirección : localhost ==="
sleep 3
xdg-open http://localhost

## RUTA PARA EJECUTAR EL SCRIPT: bash /home/victor/Projects/SGCAS/scripts/script-produccion
