# Generated by Django 3.0.5 on 2020-05-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linea_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineabase',
            options={'default_permissions': (), 'permissions': [('crear_linea_base', 'crear_linea_base'), ('cerrar_linea_base', 'cerrar_linea_base'), ('ver_linea_base', 'ver_linea_base'), ('editar_linea_base', 'editar_linea_base'), ('agregar_item_linea_base', 'agregar_item_linea_base'), ('quitar_item_linea_base', 'quitar_item_linea_base'), ('listar_item_linea_base', 'listar_item_linea_base'), ('estado_linea_base', 'estado_linea_base')]},
        ),
    ]
