# Generated by Django 3.0.5 on 2020-04-25 16:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('atributos', multiselectfield.db.fields.MultiSelectField(choices=[('Boolean', 'Boolean'), ('Char', 'Char'), ('Date', 'Date'), ('Numerico', 'Numerico')], max_length=26)),
            ],
        ),
    ]
