# Generated by Django 3.0.7 on 2020-08-20 01:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('atributos', multiselectfield.db.fields.MultiSelectField(choices=[('Boolean', 'Boolean'), ('Char', 'Char'), ('Date', 'Date'), ('Numerico', 'Numerico')], max_length=26)),
            ],
            options={
                'permissions': [('crear_tipo_item', 'crear_tipo_item'), ('adjuntar_tipo_item', 'adjuntar_tipo_item'), ('listar_tipo_item', 'listar_tipo_item'), ('editar_tipo_item', 'editar_tipo_item'), ('eliminar_tipo_item', 'eliminar_tipo_item'), ('importar_tipo_item', 'importar_tipo_item'), ('ver_tipo_item', 'ver_tipo_item')],
                'default_permissions': (),
            },
        ),
    ]
