# Generated by Django 3.0.5 on 2020-05-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoitem',
            options={'default_permissions': (), 'permissions': [('crear_tipo_item', 'crear_tipo_item'), ('adjuntar_tipo_item', 'adjuntar_tipo_item'), ('listar_tipo_item', 'listar_tipo_item'), ('editar_tipo_item', 'editar_tipo_item'), ('eliminar_tipo_item', 'eliminar_tipo_item'), ('importar_tipo_item', 'importar_tipo_item'), ('ver_tipo_item', 'ver_tipo_item')]},
        ),
    ]
