# Generated by Django 3.0.5 on 2020-05-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoitem',
            options={'permissions': [('Can add proyecto', 'Puede crear un tipo de item'), ('Can change proyecto', 'Puede editar el tipo de item'), ('Can delete proyecto', 'Puede eliminar tipo de item'), ('Can view proyecto', 'Puede visualizar tipo de item')]},
        ),
    ]
