# Generated by Django 3.0.5 on 2020-05-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_item', '0002_auto_20200501_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoitem',
            options={'permissions': [('Can add tipo de item', 'Puede crear un tipo de item'), ('Can change tipo de item', 'Puede editar el tipo de item'), ('Can delete tipo de item', 'Puede eliminar tipo de item'), ('Can view tipo de item', 'Puede visualizar tipo de item')]},
        ),
    ]
