# Generated by Django 3.0.5 on 2020-05-03 17:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipo_item', '0001_initial'),
        ('fase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('Desarrollo', 'Desarrollo'), ('Aprobado', 'Aprobado'), ('Desactivado', 'Desactivado'), ('Revision', 'Revisión'), ('LineaBase', 'Línea base')], default='Desarrollo', max_length=30)),
                ('costo', models.PositiveIntegerField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
                ('boolean', models.BooleanField(default=False)),
                ('char', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('numerico', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fase.Fase')),
                ('tipo_item', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_item.TipoItem')),
                ('usuarios_a_cargo', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
