# Generated by Django 3.0.5 on 2020-05-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'default_permissions': (), 'permissions': [('crear_item', 'crear_item'), ('aprobar_item', 'aprobar_item'), ('editar_item', 'editar_item'), ('eliminar_item', 'eliminar_item'), ('relacionar_item', 'relacionar_item'), ('ver_item', 'ver_item'), ('item_modificar_atributos', 'item_modificar_atributos'), ('cambiar_estado_item', 'cambiar_estado_item'), ('item_modificar_ti', 'item_modificar_ti'), ('item_modificar_atributos_ti', 'item_modificar_atributos_ti'), ('item_modificar_import_ti', 'item_modificar_import_ti'), ('listar_item_de_fase', 'listar_item_de_fase'), ('calcular_impacto', 'calcular_impacto')]},
        ),
    ]
