# Generated by Django 3.0.5 on 2020-05-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200429_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('Can add proyecto', 'Puede crear un item'), ('Can change proyecto', 'Puede editar el item'), ('Can delete proyecto', 'Puede eliminar un item'), ('Can view proyecto', 'Puede visualizar un item')]},
        ),
    ]
