# Generated by Django 3.0.5 on 2020-05-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200501_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('Can add item', 'Puede crear un item'), ('Can change item', 'Puede editar el item'), ('Can delete item', 'Puede eliminar un item'), ('Can view item', 'Puede visualizar un item')]},
        ),
    ]
